### ISSUE TITLE
Reduce calls to Alma API

### ISSUE THREAD

**Issue by hackartisan** [pulibrary/bibdata#1127]
Due to the concurrent hit limit of 25 hits/second, and depending on what we learn from #871 we need to find way to reduce calls to the Alma API. Likely by querying solr instead of hitting the API where possible, but also by creating new endpoints that can combine API calls and changing endpoints to return less data. Another option would be to move calls to javascript in places where we can hide the call behind a user action requirement.

This issue will act as an epic to collect specific tasks we can perform toward this goal as we discover them.

Ticketed:
- [x] new availability endpoint that accepts multiple bibs: #1118
- [x] new availability endpoint for show page #1145
- [x] orangelight use of these new endpoints pulibrary/orangelight#2382
- [x] Update the barcode#scsb endpoint to use the solr index where possible instead of the api #1185

**Comment by hackartisan** [comment]
The issues specified here were all explored and either completed or not feasible. Closing and we can open new tickets if new opportunities to reduce API calls become clear.
