### ISSUE TITLE
Alma implementation for availability#index

### ISSUE THREAD

**Issue by christinach** [pulibrary/bibdata#573]
availability GET      /availability(.:format)                   availability#index {:format=>:json}

https://github.com/pulibrary/marc_liberation/blob/master/app/controllers/availability_controller.rb
This endpoint is used for the Orangelight show page and search results and in the browse lists. 

pulibrary/orangelight#1895 has links to documentation which may be relevant

There are a lot of integration points here, and a lot of different cases in the data

- [x] Support ?id= (single bib availability used by catalog - moving to new endpoint #1145)
  - [x] Implement patron_group_charged - Blocked by process needing determined in https://github.com/pulibrary/marc_liberation/issues/903 -- implemented there as a `cdl` boolean flag
  - [x] Implement "status"
  - [x] Implement "status_label"
  - [x] Implement "label"
 api? If so are there fields we can stop providing here? could we reduce API calls to alma?
- [x] Support ?ids= (multiple bibs by id - used by catalog - moving to new endpoint #1118)
- [x] Support ?mfhd= (endpoint used by requests app - moving to new endpoint #1179)
  - returns fields needed by the request app (different from availability by bib id used in the catalog)
  - [x] Implement "status"
    - [x] child issue #937
    - [x] child issue #630
  - [x] Implement "status_label"
    - [x] child issue #937
  - [x] Implement on_reserve - child issue #846 - (https://github.com/tulibraries/alma_rb/issues/62 -> DONE)
  - [x] Implement location.
    * Should NOT be 852b, this is old info from Voyager that will not be updated. Pull from the first item in the holding.
  - [x] Implement pickup_location_id - child issue #848
    - Used by requests app. But they are about to migrate off of it. Once they've migrated off, is orangelight the only client consuming this
  - [x] Implement copy_number
- [x] Support ?barcodes=
- [x] Support ?scsb_id=
- [x] Ensure bound-withs are tested - child issue #1239
- [x] Remove support for ?mfhd_serial= # We don't think we have a use case for this endpoint anymore, with the simplified logic we're doing in orangelight

Barcodes/SCSB use SCSB, should work.

**Comment by tpendragon** [comment]
@mzelesky @christinach I'm trying to do `on_reserve`, I see the comments on https://github.com/pulibrary/marc_liberation/issues/641 but it's not clear to me what `on_reserve: Y` means. Does that mean it's in a course reserve?

**Comment by christinach** [comment]
> @mzelesky @christinach I'm trying to do `on_reserve`, I see the comments on #641 but it's not clear to me what `on_reserve: Y` means. Does that mean it's in a course reserve?

Yes

**Comment by hackartisan** [comment]
Description copied here from pulibrary/alma_experimentation#30 that may be helpful:

Availability logic currently is in VoyagerHelpers. https://github.com/pulibrary/voyager_helpers/blob/37b62ad83ed2f1af6185e54534d901e23e5fdf30/lib/voyager_helpers/liberator.rb#L229

In Alma, PO lines for items can be returned in the Publishing jobs. Based on the location of a holding, Bibdata should retrieve the order status of an attached PO line. If it is an electronic resource, order status does not need to be retrieved. There are likely other criteria to look at as well.

**Comment by hackartisan** [comment]
https://github.com/pulibrary/marc_liberation/issues/629#issuecomment-696933001 gives info about Alma's availability values which may also be relevant

**Comment by carolyncole** [comment]
@hackartisan For the `availability?mfhd=` 
Fields we do not use, but are currently present: id, item_sequence_number, due_date, patron_group_charged, enum, label(?), location(?). (I put question marks, because I do not see them at first glance, but they seem like things we might use...)
Endpoint the fields we use are: barcode, location, copy_number, status, on_reserve, item_type, pickup_location_id, pickup_location_code, enum_display, chron, status_label
