### ISSUE TITLE
Change the Subject -- implement correct alternative terms with traject technique

### ISSUE THREAD

**Issue by christinach** [pulibrary/bibdata#595]
## Background 

* [Technical project plan](https://docs.google.com/document/d/1pnLH4GVVAwfl-mu_Ksb8XPjoy0MaM8qlgxeGtnb6hJQ/edit)
* [marc_cleanup gem](https://github.com/pulibrary/marc_cleanup)
* [Subject headings mappings - work in progress](https://docs.google.com/spreadsheets/d/191sqH8tqpc0EFv2l1U9mh1-S1K4YFrtUQAaUlWhb4eg/edit?ts=60888289#gid=0)

{
"id":["65071"],
"subject_display":["Illegal aliens"],
"lc_subject_display":["Illegal aliens"],
"subject_facet":["Illegal aliens"],
"subject_topic_facet":["Illegal aliens"]
}

Proposed version:
{
"id":["65071"],
"subject_display":["Undocumented immigrants"],
"subject_unstem_search":["Illegal aliens","Undocumented immigrants"]
"lc_subject_display":["Undocumented immigrants"],
"subject_facet":["Illegal aliens","Undocumented immigrants"],
"subject_topic_facet":["Illegal aliens","Undocumented immigrants"]
}

**ACCEPTANCE CRITERIA**
- [x] At index time we will index synonyms, so we'll need a synonym file 
- [x] If you search for "Illegal aliens" it finds items that were cataloged as "Undocumented immigrants"
- [x] The subject term "illegal aliens" should *NOT* appear in the catalog anywhere (in facets or on show page) but it will still be indexed

**Comment by mzelesky** [comment]
Updated:

{
"id":["65071"],
"subject_display":["Undocumented immigrants"],
"subject_unstem_search":["Illegal aliens","Undocumented immigrants"]
"lc_subject_display":["Undocumented immigrants"],
"subject_facet":["Undocumented immigrants"], # Subject browse list field
"subject_topic_facet":["Undocumented immigrants"] # Subject facet search results
}

**Comment by tampakis** [comment]
{
"id": ["10989023"],
"subject_display": ["Undocumented immigrants—Africa—Drama","Undocumented immigrants—Europe—Drama"],
"lc_subject_display": ["Undocumented immigrants—Africa—Drama","Undocumented immigrants—Europe—Drama"],
"subject_facet": ["Undocumented immigrants—Africa—Drama","Undocumented immigrants—Europe—Drama"],
"subject_topic_facet": ["Undocumented immigrants","Africa","Europe"],
"replace_subject_facet": ["Illegal aliens—Africa—Drama","Illegal aliens—Europe—Drama"]
}

**Comment by jpstroop** [comment]
Something else to consider as a part of this project. Staff a putting a lot of time into researching why these headings are offensive and why the replacement is more appropriate. Should we build the ability to display the raitionale for each change into the UI? (maybe something you can expand/collapse and read next to the heading itself?) Chances are that the people using these headings would appreciate knowing about the change, and it's a good visible demonstration of the changes we are trying to make.

**Comment by christinach** [comment]
https://catalog.princeton.edu/catalog/99650713506421/raw use this fixture for start
