### ISSUE TITLE
Replicate necessary MarcLiberation controller functionality from Voyager to Alma

### ISSUE THREAD

**Issue by tpendragon** [pulibrary/bibdata#654]
Ordered by most hits (in just under 1 week) according to the [datadog stats](https://app.datadoghq.com/logs/analytics?agg_q=%40controller%2C%40action%2C%40format&cols=host%2Cservice%2C%40http.url_details.queryString.q%2C%40action%2C%40format&from_ts=1604271119706&index=&live=true&messageDisplay=inline&panel=%22%22&query=source%3Aruby+service%3Abibdata+-%40controller%3A%22Locations%3A%3AHoldingLocationsController%22+-%40controller%3A%22Locations%3A%3ADeliveryLocationsController%22+-%40controller%3A%22HighVoltage%3A%3APagesController%22++-%40controller%3A%22Users%3A%3AOmniauthCallbacksController%22&stream_sort=desc&to_ts=1606863119706&top_n=10&viz=query_table)

Group 0 (this one gets the most hits, and is tracked in its own top-level issue):
- [ ] availability GET      /availability(.:format)                   availability#index {:format=>:json} - #573

Group 1: Thousands of hits:
- [x] show_bib GET      /bibliographic/:bib_id(.:format)          bibliographic#bib {:format=>:xml} - #709 done (see lower in the list for follow-up)
- [x] GET      /bibliographic/:bib_id/items(.:format)    bibliographic#bib_items {:format=>:json} - #751, #1055
- [x] courses GET      /courses(.:format)                        courses#index {:format=>:json} - #931 - wontfix: physical reserves are not in use
- [x] GET      /patron/:patron_id                        patron#patron_info {:format=>:json, :patron_id=>/[^\/]+/} - #932
- [x] GET      /barcode/:barcode/scsb(.:format)          barcode#scsb {:format=>:xml} - #933

Group 2: Hundreds of hits:
- [x] GET      /bibliographic/:bib_id/solr(.:format)     bibliographic#bib_solr - #725
- [x] GET      /bibliographic/:bib_id/jsonld(.:format)   bibliographic#bib_jsonld - #725
- [x] bib_ids GET      /bib_ids(.:format)                        courses#bibs {:format=>:json} - #934 - wontfix: physical reserves are not in use
- [ ] POST     /bibliographic(.:format)                  bibliographic#update - #748
- [x] bibliographic GET      /bibliographic(.:format)                  bibliographic#index {:format=>:txt}

Single digit use counts:
- [x] GET      /bibliographic/:bib_id/holdings(.:format) bibliographic#bib_holdings {:format=>:xml} - #733 (implemented in json; usage stats were very low so we are considering this sufficient unless / until someone notifies us of an automated use case)
- [x] GET      /holdings/:holding_id(.:format)           holdings#holding {:format=>:json} - Do not migrate
- [x] GET      /holdings/:holding_id/items(.:format)     holdings#holding_items {:format=>:json}  - Do not migrate
- [x] holdings GET      /holdings(.:format)                       holdings#index {:format=>:txt} - Do not migrate
- [x]  items GET      /items(.:format)                          items#index {:format=>:txt} - Do not migrate
- [x] GET      /items/:item_id(.:format)                 items#item {:format=>:json} https://github.com/pulibrary/marc_liberation/issues/734 - Do not migrate
- [ ] show_bib GET      /bibliographic/:bib_id(.:format)          bibliographic#bib {:format=>:xml} - lower-priority follow up ticket: #712

No usage in the logs:
- [x]  barcode GET      /barcode(.:format)                        barcode#index {:format=>:txt} - No code change is needed here, so it's fine to either keep it or delete it.
- [x] show_barcode GET      /barcode/:barcode(.:format)               barcode#barcode {:format=>:xml} # this didn't have an explicit use case, was just a step on the way to barcode#scsb so we don't need to do this one - It would be easy to implement this as equivalent to or a slight variation on #scsb, but we'll wait for a ticket that articulates a use case for this.
- [x] GET      /codes/:location(.:format)                codes#locations {:format=>:json} - This would essentially be just a wrapper around the alma API. It would be easy to write if a use case presented itself but we don't need it.
- [x] GET      /patron/:patron_id/codes                  patron#patron_codes {:format=>:json, :patron_id=>/[^\/]+/} # Kevin says this doesn't have a use case and is not used; just delete (confirmed with Mark)

Notes:
- The alma API doesn't provide access to holdings or items just by holdings or item id.
  - These endpoints aren't in use by any system integrations
  - If catalogers need this information, they can search Alma directly
  - The only implementation for these endpoints would involve maintaining a sidecar database, which is not justified by any use cases
  - We will delete these endpoints instead of migrating
  - The only use case we might have would be for generating certain hypothetical reports.

**Comment by hackartisan** [comment]
Things we know:

- Records with no items: https://github.com/pulibrary/marc_liberation/issues/642

**Comment by hackartisan** [comment]
Closing this epic; it's outlived its usefulness and the remaining tickets are well-known.
