### ISSUE TITLE
Build, provision, deploy production alma infrastructure

### ISSUE THREAD

**Issue by hackartisan** [pulibrary/bibdata#983]
We will build new production infrastructure to empower a switchover migration. (Once migration is complete we'll turn off the old bibdata boxes) 

The current production Alma will be moved to their production infrastructure wholesale. Then our sandbox will be deleted and our production data will be copied over into a "premium sandbox".

Final infrastructure will be arranged as follows:
* Bibdata (see also notes in #991)
  * [x] Production (x2 - call them `bibdata-alma1` and `bibdata-alma2`): these will pull data from Alma prod
  * [x] Worker (x1 - this box exists as `bibdata-alma-worker-qa1` but please rename to `bibdata-alma-worker1`): will pull data from Alma prod https://github.com/pulibrary/princeton_ansible/issues/1478
  * [x] Staging (x1 - this is the one we are using - `bibdata-alma-staging1`): After go-live, this will pull data from the Alma premium sandbox 
  * [x] Staging worker (x1 - `bibdata-alma-worker-staging1`): friend of above, see #1417 
* Orangelight
  * [x] Production (x2 - call them `catalog1` and `catalog2`): will pull data from bibdata prod, Alma prod
  * [x] QA (x1 - this box exists as `lib-orange-alma-qa1` but please rename to `catalog-qa1`): will pull data from bibdata prod, Alma prod
  * [ ] Staging (x2 - call them `catalog-staging1` and `catalog-staging2`): pull data from bibdata staging, Alma Premium sandbox
  * [x] Workers (x3 - call them `catalog-indexer1`, `catalog-indexer2`, `catalog-indexer3`): used to build the browse indexes
* AWS webhook listener
  * [x] Production: We currently have one webhook listener which is deployed as production.
  * [x] Staging: We will need to deploy a staging listener to listen for events coming from the premium sandbox - #968
* SQS queues: Initially the production listener will write to all queues. Once we have the premium sandbox the staging listener will write those mesages to the staging queue.
  * [x] Staging: Staging listener will write here.
  * [x] Production: We need an SQS queue for production; production webhook listener will post here
  * [x] QA: production webhook listener will duplicate messages to this queue
* [x] Rabbit mq configurations: https://github.com/pulibrary/orangelight/issues/2319

Child issues:
- [x] https://github.com/pulibrary/princeton_ansible/issues/1459
- [ ] ~~pulibrary/princeton_ansible#2072~~

Keys
* Security considerations:
  * If the “my account” functionality is hijacked somehow then it can’t be used to write more than that feature can itself write.
  * Another consideration might be a malicious actor getting onto a box.
* Bibdata will have a global readonly key, as it currently does
* Orangelight will have a write key limited to request app requirements
* In general write keys will be created on a per-feature, per-app basis.
* Write an ADR for this? - https://github.com/pulibrary/princeton_ansible/pull/2329

**Comment by hackartisan** [comment]
cc @kayiwa we're not ready to work on these yet but just so you have a sense of what we're planning

**Comment by hackartisan** [comment]
I think there was a question about paths on this issue, perhaps in relation to the name change of the repo. The deploy target should probably be changed to `/opt/bibdata`.

**Comment by tpendragon** [comment]
This is what's configured now.

![Current State](https://user-images.githubusercontent.com/2806645/119047890-58600f00-b973-11eb-84bd-c369bf036390.png)

Missing steps:
- [ ] Merge https://github.com/pulibrary/bibdata/pull/1344
- [ ] Fix Redis configuration for bibdata1/2/worker1 to use a single redis instance for Sidekiq.

**Comment by hackartisan** [comment]
This is the chart I made for reviewing all the integrations: https://docs.google.com/spreadsheets/d/1NNxpLQ5gRTOf0eGXIXgy6Qk4b6UeiBV4YHa52FNH6C4/edit?usp=sharing

I'm closing this since prod infra is done and we'll do orangelight staging infra once the premium sandbox is available, ticketed as #2546
